config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  root 'posts#index'
  resources :posts
  resources :users, only: %i[index edit update destroy]

  resources :posts do
    resources :comments, only: [:create]
    member do
      put 'like', to: 'posts#like'
      put 'unlike', to: 'posts#unlike'
    end
  end
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  acts_as_votable

  belongs_to :user
  has_many :comments, dependent: :destroy

  has_one_attached :image
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true, uniqueness: true

  has_many :posts
  has_many :comments
  acts_as_voter
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to @post, notice: 'Comment was successfully created.'
    else
      redirect_to @post, alert: 'Error creating comment.'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_post, only: %i[show edit update destroy like unlike]

  def index
    @posts = if params[:filter] == 'my_posts'
               current_user.posts.order(:title).page(params[:page]).per(6)
             else
               Post.order(:title).page(params[:page]).per(6)
             end
  end

  def show
    @post = Post.find(params[:id])
    @comment = @post.comments.build
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      flash.now[:alert] = 'Error creating post.'
      render :new
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: 'Post was successfully destroyed.'
  end

  def like
    @post.liked_by current_user
    respond_to do |format|
      format.html { redirect_to @post }
      format.js   { render layout: false }
    end
  end

  def unlike
    @post.unliked_by current_user
    respond_to do |format|
      format.html { redirect_to @post }
      format.js   { render layout: false }
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description, :image)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[edit update destroy]

  def index
    @users = User.all
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to users_path, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, notice: 'User was successfully destroyed.'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :name, :password)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag 'application' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">    <%= stylesheet_link_tag "application" %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </head>

  <header  class="py-4 shadow">
    <h1>Posts blogs store</h1>
  </header>

  <body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-3">
        <div class="sidebar">
          <ul class="nav flex-column">
            <div class="new-post-link nav-item">
              <%= link_to 'Sign In', new_user_session_path, class: "nav-link"  %>
              <% if current_user.present? %>
                <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "nav-link"  %>
              <% end %>
              <%= link_to "New Post", new_post_path, class: "nav-link" %>
            </div>
            <li class="nav-item">
              <a class="nav-link active" href="/">Главная</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Категория 1</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Категория 2</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Категория 3</a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-9">
        <%= yield %>
      </div>
    </div>
  </div>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "posts/shared/form" %>

<%= link_to "Back to Posts", posts_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<% if current_user.present? %>
  <%= form_tag(root_path, method: 'get', class: 'form') do %>
    <%= submit_tag('All Posts', name: 'filter', value: 'all', class: 'filter-button') %>
    <%= submit_tag('My Posts', name: 'filter', value: 'my_posts', class: 'filter-button') %>
  <% end %>
<% end %>

<div class="container-fluid">
  <%= render 'posts/shared/post_list' %>
</div>

<%= paginate @posts %>

app/views/posts/like.js.erb
$("#like-button").hide();
$("#unlike-button").show();

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "posts/shared/form" %>

<%= link_to "Back to Posts", posts_path %>

app/views/posts/shared/_comment_area.html.erb
<% @post.comments.each do |comment| %>
  <p>
    <strong><%= comment.user.username if comment.user %></strong>
    <%= comment.content %>
  </p>
<% end %>
<%= form_with(model: @comment, url: post_comments_path(@post)) do |form| %>
  <%= form.text_field :content %>
  <%= form.submit "Post Comment" %>
<% end %>

app/views/posts/shared/_form.html.erb
<%= form_with(model: @post, url: @post.persisted? ? post_path(@post) : posts_path, local: true) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :image, class: "form-label" %>
    <%= form.file_field :image, class: "form-control" %>
  </div>

  <div>
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/shared/_post_list.html.erb
<div class="row">
  <div class="col-md-9">
    <div class="container content-container">
      <div class="row row-cols-1 row-cols-md-3 g-4 justify-content-center text-center">
        <% @posts.each do |post| %>
          <div class="col mx-auto">
            <div class="card h-100">
              <% if post.image.attached? %>
                <%= image_tag(post.image, class: "card-img-top content-image") %>
              <% else %>
                <div class="placeholder-image"></div>
              <% end %>
              <div class="card-body">
                <h5 class="card-title content-title"><%= link_to post.title, post_path(post) %></h5>
                <p class="card-text"><%= post.description %></p>
                <div class="d-grid gap-2">
                  <% if current_user == post.user %>
                    <%= link_to "Edit", edit_post_path(post), class: "btn btn-custom btn-sm rounded-pill fw-bold shadow-sm" %>
                    <%= link_to "Delete", post_path(post), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger btn-sm rounded-pill fw-bold shadow-sm" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<%= notice if notice.present?%>
<div class="content">
  <div class="container">
    <div class="row">
      <div class=""> <!-- col-xs-12 col-sm-4 -->
        <div>
          <%= image_tag(@post.image, class: " col-sm-4") if @post.image.attached? %>
          <div class="card-body">
            <h1 class="card-title text-primary"><%= @post.title %></h1>
            <p class="card-text"><%= @post.description %></p>
            <p>Likes: <span class="likes-count"><%= @post.get_likes.size %></span></p>

            <% if user_signed_in? %>
              <% if current_user.voted_for?(@post) %>
                <%= link_to unlike_post_path(@post), method: :put, remote: true, class: "like-dislike-button" do %>
                  <i class="fas fa-thumbs-up"></i> Unlike
                <% end %>
              <% else %>
                <%= link_to like_post_path(@post), method: :put, remote: true, class: "like-dislike-button" do %>
                  <i class="far fa-thumbs-up"></i> Like
                <% end %>
              <% end %>
            <% end %>

            <div class="button-group">
              <%= link_to "Edit", edit_post_path(@post), class: "btn btn-outline-primary btn-sm" %>
              <%= link_to "Back to Posts", posts_path, class: "btn btn-outline-secondary btn-sm" %>
            </div>
            <%= render 'posts/shared/comment_area' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/unlike.js.erb
$("#unlike-button").hide();
$("#like-button").show();